### ISSUE TITLE
#2 default.blade.php等の作成

### ISSUE THREAD

**Issue by takahiro-yokoyama** [takahiro-yokoyama/laravel_maps_team_b#2]
issue/2で、

resources/views/layouts　のなかに

･default.blade.php
･logged_in.blade.php
･not_logged_in.blade.php
を作成してください。

cssも4種類作成してください。

**Comment by z-kotomi** [comment]
ログインしていない状態だとlogged_in.blade.phpはエラー出る仕様なので、ログインしていない状態で編集したい場合はユーザー名後の{{}}カッコを外す
